import { z } from "zod";
import { canonicalizeGitHubLogin } from "../server/github-principals.js";

const SafeAbsolutePath = z.string().min(2).max(180)
  .regex(/^\/[A-Za-z0-9._/-]+$/, "path contains unsupported characters")
  .refine((path) => !path.includes("//") && path.split("/").every((segment) => segment !== "." && segment !== ".."), "path must be normalized without traversal");
const Domain = z.string().min(1).max(253).regex(/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/, "domain must be canonical ASCII DNS name");
const GitHubLogin = z.string().refine((login) => {
  try {
    return canonicalizeGitHubLogin(login) === login;
  } catch {
    return false;
  }
}, "GitHub login must be canonical");

const DeploymentTemplateInputSchema = z.object({
  domain: Domain,
  listener: z.union([
    z.object({ kind: z.literal("unix"), path: SafeAbsolutePath }).strict(),
    z.object({ kind: z.literal("tcp"), host: z.literal("127.0.0.1"), port: z.number().int().min(1024).max(65535), fallback: z.literal(true) }).strict(),
  ]),
  oauth2ProxyPort: z.number().int().min(1024).max(65535),
  proxySecret: z.string().min(43).max(128).regex(/^[A-Za-z0-9_-]+$/),
  githubLogins: z.array(GitHubLogin).min(1),
  oauthClientId: z.string().min(1).max(128).regex(/^[A-Za-z0-9._-]+$/),
  oauthClientSecretFile: SafeAbsolutePath,
  cookieSecretFile: SafeAbsolutePath,
  tlsCertificate: SafeAbsolutePath,
  tlsCertificateKey: SafeAbsolutePath,
  acmeWebroot: SafeAbsolutePath,
}).strict().superRefine((input, context) => {
  const seen = new Set<string>();
  input.githubLogins.forEach((login, index) => {
    if (seen.has(login)) {
      context.addIssue({ code: z.ZodIssueCode.custom, path: ["githubLogins", index], message: "duplicate GitHub login" });
    }
    seen.add(login);
  });
  if (input.listener.kind === "tcp" && input.listener.port === input.oauth2ProxyPort) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["oauth2ProxyPort"], message: "oauth2-proxy port collides with app fallback" });
  }
});

export type DeploymentTemplateInput = z.infer<typeof DeploymentTemplateInputSchema>;

export interface RenderedDeploymentTemplates {
  nginxSite: string;
  oauth2ProxyConfig: string;
  redacted: {
    nginxSite: string;
    oauth2ProxyConfig: string;
  };
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function appProxyDirectives(secret: string): string {
  return `    auth_request /oauth2/auth;
    auth_request_set $pi_together_login $upstream_http_x_auth_request_user;

    proxy_pass_request_headers off;
    proxy_set_header Host $host;
    proxy_set_header Accept $http_accept;
    proxy_set_header Content-Type $http_content_type;
    proxy_set_header Content-Length $content_length;
    proxy_set_header Origin $http_origin;
    proxy_set_header Last-Event-ID $http_last_event_id;
    proxy_set_header X-Pi-Together-Proxy-Secret ${secret};
    proxy_set_header X-Pi-Together-Login $pi_together_login;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_pass http://pi_together_app;`;
}

function oauthProxyDirectives(port: number, includeCookie: boolean, includeBody: boolean): string {
  return `    proxy_pass_request_headers off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
${includeCookie ? "    proxy_set_header Cookie $http_cookie;\n" : ""}${includeBody
  ? "    proxy_set_header Content-Type $http_content_type;\n    proxy_set_header Content-Length $content_length;\n"
  : "    proxy_set_header Content-Length \"\";\n"}    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_pass http://127.0.0.1:${port};`;
}

export function renderNginxChallengeSite(domainValue: string, webrootValue: string): string {
  const domain = Domain.parse(domainValue);
  const webroot = SafeAbsolutePath.parse(webrootValue);
  return `# Generated by Pi Together for initial ACME validation. Do not edit.
server {
  listen 80;
  listen [::]:80;
  server_name ${domain};

  location ^~ /.well-known/acme-challenge/ {
    root ${webroot};
    default_type text/plain;
    try_files $uri =404;
  }

  location / {
    return 404;
  }
}
`;
}

export function renderNginxSite(inputValue: DeploymentTemplateInput): string {
  const input = DeploymentTemplateInputSchema.parse(inputValue);
  const appServer = input.listener.kind === "unix"
    ? `unix:${input.listener.path}`
    : `${input.listener.host}:${input.listener.port}`;
  const app = appProxyDirectives(input.proxySecret);
  const oauthBrowser = oauthProxyDirectives(input.oauth2ProxyPort, true, true);
  const oauthAuth = oauthProxyDirectives(input.oauth2ProxyPort, true, false);

  return `# Generated by Pi Together. Do not edit.
upstream pi_together_app {
  server ${appServer};
  keepalive 16;
}

server {
  listen 80;
  listen [::]:80;
  server_name ${input.domain};

  location ^~ /.well-known/acme-challenge/ {
    root ${input.acmeWebroot};
    default_type text/plain;
    try_files $uri =404;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name ${input.domain};
  server_tokens off;

  ssl_certificate ${input.tlsCertificate};
  ssl_certificate_key ${input.tlsCertificateKey};
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_tickets off;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header Content-Security-Policy "frame-ancestors 'none'; base-uri 'none'; object-src 'none'" always;
  add_header Permissions-Policy "camera=(), geolocation=(), microphone=()" always;
  add_header Referrer-Policy "no-referrer" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Frame-Options "DENY" always;

  client_max_body_size 1m;

  location /oauth2/ {
${oauthBrowser}
  }

  location = /oauth2/auth {
    internal;
    proxy_pass_request_body off;
${oauthAuth}
  }

  location @oauth2_signin {
    return 302 /oauth2/sign_in?rd=$scheme://$host$request_uri;
  }

  location /api/ {
${app}
  }

  location = /events {
${app}
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_cache off;
    gzip off;
    proxy_read_timeout 1h;
    proxy_send_timeout 1h;
    proxy_hide_header Cache-Control;
    proxy_hide_header X-Accel-Buffering;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Content-Security-Policy "frame-ancestors 'none'; base-uri 'none'; object-src 'none'" always;
    add_header Permissions-Policy "camera=(), geolocation=(), microphone=()" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Cache-Control "no-cache, no-transform" always;
    add_header X-Accel-Buffering "no" always;
  }

  location / {
    error_page 401 = @oauth2_signin;
${app}
  }
}
`;
}

export function renderNginxFunnelEdge(inputValue: DeploymentTemplateInput, options: { port?: number; serviceUser: string; runtimeDirectory?: string }): string {
  const input = DeploymentTemplateInputSchema.parse(inputValue);
  const port = options.port ?? 43118;
  const runtimeDirectory = SafeAbsolutePath.parse(options.runtimeDirectory ?? "/run/pi-together-edge");
  if (!/^[a-z_][a-z0-9_-]{0,31}$/.test(options.serviceUser)) throw new Error("invalid Funnel edge user");
  if (!Number.isInteger(port) || port < 1024 || port > 65535 || port === input.oauth2ProxyPort) throw new Error("invalid Funnel edge port");
  const appServer = input.listener.kind === "unix" ? `unix:${input.listener.path}` : `${input.listener.host}:${input.listener.port}`;
  const app = appProxyDirectives(input.proxySecret);
  const oauthBrowser = oauthProxyDirectives(input.oauth2ProxyPort, true, true);
  const oauthAuth = oauthProxyDirectives(input.oauth2ProxyPort, true, false);
  const edge = `upstream pi_together_app {
  server ${appServer};
  keepalive 16;
}
server {
  listen 127.0.0.1:${port};
  server_name ${input.domain};
  server_tokens off;
  client_max_body_size 1m;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header Content-Security-Policy "frame-ancestors 'none'; base-uri 'none'; object-src 'none'" always;
  add_header Permissions-Policy "camera=(), geolocation=(), microphone=()" always;
  add_header Referrer-Policy "no-referrer" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Frame-Options "DENY" always;

  location /oauth2/ {
${oauthBrowser}
  }
  location = /oauth2/auth {
    internal;
    proxy_pass_request_body off;
${oauthAuth}
  }
  location @oauth2_signin {
    return 302 https://${input.domain}/oauth2/sign_in?rd=https://${input.domain}$request_uri;
  }
  location /api/ {
${app}
  }
  location = /events {
${app}
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_cache off;
    gzip off;
    proxy_read_timeout 1h;
    proxy_send_timeout 1h;
    proxy_hide_header Cache-Control;
    proxy_hide_header X-Accel-Buffering;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Content-Security-Policy "frame-ancestors 'none'; base-uri 'none'; object-src 'none'" always;
    add_header Permissions-Policy "camera=(), geolocation=(), microphone=()" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Cache-Control "no-cache, no-transform" always;
    add_header X-Accel-Buffering "no" always;
  }
  location / {
    error_page 401 = @oauth2_signin;
${app}
  }
}
`;
  return `# Generated by Pi Together for Tailscale Funnel. Do not edit.
user ${options.serviceUser};
worker_processes 1;
pid ${runtimeDirectory}/nginx-edge.pid;
error_log stderr warn;
events { worker_connections 256; }
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log off;
  client_body_temp_path ${runtimeDirectory}/nginx-client-body-temp;
  proxy_temp_path ${runtimeDirectory}/nginx-proxy-temp;
  fastcgi_temp_path ${runtimeDirectory}/nginx-fastcgi-temp;
  uwsgi_temp_path ${runtimeDirectory}/nginx-uwsgi-temp;
  scgi_temp_path ${runtimeDirectory}/nginx-scgi-temp;
${edge.split("\n").map((line) => `  ${line}`).join("\n")}}
`;
}

export function renderOauth2ProxyConfig(inputValue: DeploymentTemplateInput): string {
  const input = DeploymentTemplateInputSchema.parse(inputValue);
  const logins = [...input.githubLogins].sort();
  return `# Generated by Pi Together. Contains secret-file paths; mode 0600.
provider = "github"
http_address = "127.0.0.1:${input.oauth2ProxyPort}"
reverse_proxy = true
redirect_url = "https://${input.domain}/oauth2/callback"
whitelist_domains = ["${input.domain}"]
upstreams = ["static://202"]

client_id = ${tomlString(input.oauthClientId)}
client_secret_file = ${tomlString(input.oauthClientSecretFile)}
cookie_secret_file = ${tomlString(input.cookieSecretFile)}

github_users = ${tomlArray(logins)}
email_domains = ["*"]

cookie_name = "__Host-pi_together"
cookie_path = "/"
cookie_secure = true
cookie_httponly = true
cookie_samesite = "lax"
cookie_csrf_samesite = "lax"
cookie_csrf_per_request = true
cookie_csrf_per_request_limit = 8
cookie_expire = "8h"

set_xauthrequest = true
set_authorization_header = false
set_basic_auth = false
pass_access_token = false
pass_authorization_header = false
pass_basic_auth = false
pass_user_headers = false
pass_host_header = false
skip_auth_strip_headers = false
skip_auth_preflight = false
show_debug_on_error = false
request_logging = false
auth_logging = true
standard_logging = true
`;
}

export function renderDeploymentTemplates(inputValue: DeploymentTemplateInput): RenderedDeploymentTemplates {
  const input = DeploymentTemplateInputSchema.parse(inputValue);
  const nginxSite = renderNginxSite(input);
  const oauth2ProxyConfig = renderOauth2ProxyConfig(input);
  return {
    nginxSite,
    oauth2ProxyConfig,
    redacted: {
      nginxSite: nginxSite.replaceAll(input.proxySecret, "<redacted-proxy-secret>"),
      oauth2ProxyConfig,
    },
  };
}

export const OAUTH2_PROXY_RELEASE = {
  version: "7.15.3",
  baseUrl: "https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v7.15.3",
  assets: {
    "linux-x64": {
      archive: "oauth2-proxy-v7.15.3.linux-amd64.tar.gz",
      sha256: "0ae5a43adde4d6c5081ba018e70a76041f496377b12a173da36b419082dd1ab6",
    },
    "linux-arm64": {
      archive: "oauth2-proxy-v7.15.3.linux-arm64.tar.gz",
      sha256: "62452322a71e958d4d6911f799bc07921212a5f3bc45e39b63746e422d52ea33",
    },
  },
} as const;
